const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const ctx={Date,Utilities:{formatDate:()=>{throw Error('unexpected date object')}},SpreadsheetApp:{openById:()=>({getSpreadsheetTimeZone:()=> 'Europe/Sofia'})}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('sheets/noseway.gs','utf8'),ctx);
assert.equal(ctx.nwDate_('09/08/2026'),'2026-08-09');
assert.equal(ctx.nwDate_('Whole period'),'Whole period');
assert.throws(()=>ctx.nwDate_('31/02/2026'));
assert.throws(()=>ctx.nwValidate_({rows:[]}));
assert.throws(()=>ctx.nwValidate_({rows:{}}));
assert.throws(()=>ctx.nwValidate_({rows:[{key:'a',name:'one',kind:'meta'},{key:'a',name:'two',kind:'meta'}]}));
assert.notEqual(ctx.nwVersion_({link:'same',copy:'old'}),ctx.nwVersion_({link:'same',copy:'new'}));
const section=ctx.nwSection_({section:'Batch 01',batch:'batch-legacy-001'});
assert.equal(section.length,14);
assert.equal(section[11],'section:Batch 01');
assert.equal(section[13],'batch-legacy-001');
console.log('10 sheet validation/date/version/layout checks passed');
